name: Test
on:
  push:
    branches: main
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run tests
      run: gem install minitest --no-document >/dev/null && ruby test/*_test.rb
